"""empty message

Revision ID: 665c3735b4eb
Revises: e1a77fc7ceb2
Create Date: 2022-08-06 15:38:47.294480

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "665c3735b4eb"
down_revision = "e1a77fc7ceb2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("updated_on", sa.DateTime(), nullable=True))
    op.alter_column(
        "task",
        "created_on",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("task", "finished_on")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column(
            "finished_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "task",
        "created_on",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("task", "updated_on")
    # ### end Alembic commands ###
