"""Edit create and update field

Revision ID: 81d384d9e8fa
Revises: c969fd225319
Create Date: 2022-08-06 15:47:25.406534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "81d384d9e8fa"
down_revision = "c969fd225319"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task", "updated_on", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task", "updated_on", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
