"""Edit create and update field

Revision ID: c6d0eea48485
Revises: 7772fbeced75
Create Date: 2022-08-06 16:05:01.914406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c6d0eea48485"
down_revision = "7772fbeced75"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task",
        "create_on",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "task", "updated_on", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task", "updated_on", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "task",
        "create_on",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
