"""empty message

Revision ID: c969fd225319
Revises: 1939751e203b
Create Date: 2022-08-06 15:43:55.465767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c969fd225319"
down_revision = "1939751e203b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task", "updated_on", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task", "updated_on", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###
