"""rename employ_comment to employee_comments from task table

Revision ID: f9593d97d255
Revises: e2c877a4e410
Create Date: 2022-07-30 12:52:23.884157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f9593d97d255"
down_revision = "e2c877a4e410"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task", sa.Column("employee_comments", sa.String(length=255), nullable=False)
    )
    op.drop_column("task", "employ_comments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column(
            "employ_comments",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("task", "employee_comments")
    # ### end Alembic commands ###
